export const DEPARTMENT_GROUPS = [
  {
    category: 'BPM / IT & Technology',
    options: [
      'BPM',
      'Analytics / KPO / Research',
      'BPM / BPO',
      'IT Services',
      'IT Services & Consulting',
      'Technology',
      'Electronic Components / Semiconductors',
      'Electronics Manufacturing',
      'Emerging Technologies',
      'Hardware & Networking',
      'Internet',
      'Software Product',
    ],
  },
  {
    category: 'BFSI',
    options: [
      'Banking',
      'Financial Services',
      'FinTech / Payments',
      'Insurance',
      'Investment Banking / Venture Capital / Private Equity',
      'NBFC',
    ],
  },
  {
    category: 'Education',
    options: [
      'Education / Training',
      'E-Learning / EdTech',
    ],
  },
  {
    category: 'Manufacturing & Production',
    options: [
      'Auto Components',
      'Automotive',
      'Building Material',
      'Chemicals',
      'Defense & Aerospace',
      'Electrical Equipment',
      'Fertilizers / Agrochemicals',
      'Food Processing',
      'Furniture / Furnishing',
      'Industrial Automation',
      'Industrial Equipment / Machinery',
      'Iron & Steel',
      'Metals & Mining',
      'Packaging / Containers',
      'Paper and Forest Products',
      'Petroleum / Gas / Energy',
      'Plastic / Rubber',
      'Printing & Publishing',
      'Textiles / Garments / Accessories',
      'Tyres',
    ],
  },
  {
    category: 'Healthcare & Life Sciences',
    options: [
      'Animal Health',
      'Biotechnology',
      'Clinical Research',
      'Medical Devices / Equipment',
      'Medical Services / Hospital',
      'Pharmaceutical / Life Sciences',
    ],
  },
  {
    category: 'Professional Services',
    options: [
      'Accounting / Auditing',
      'Architecture / Interior Design',
      'Consulting',
      'Content Development / Language',
      'Design',
      'Engineering & Construction',
      'HR / Recruitment / RPO',
      'Legal',
      'Management Consulting',
      'Market Research',
      'Real Estate',
      'Staffing / Outsourcing',
    ],
  },
  {
    category: 'Consumer, Retail & Hospitality',
    options: [
      'Beauty & Personal Care',
      'Consumer Electronics / Appliances',
      'E-Commerce',
      'FMCG',
      'Gems & Jewellery',
      'Hotels / Restaurants / Airlines / Travel',
      'Leather',
      'Media / Entertainment / Advertising',
      'Retail',
      'Sports / Leisure / Fitness',
    ],
  },
  {
    category: 'Logistics & Infrastructure',
    options: [
      'Courier / Logistics / Warehousing / Transportation',
      'Infrastructure / Urban Development',
      'Ports and Shipping',
      'Power',
      'Railways',
      'Roads & Highways',
      'Water Treatment / Waste Management',
    ],
  },
  {
    category: 'Others',
    options: [
      'Agriculture / Dairy / Fishing',
      'Aviation',
      'Event Management',
      'Facilities Management',
      'Garment / Merchandising',
      'Government / Public Administration',
      'Non-Profit / Volunteering',
      'Oil & Gas / Energy',
      'Public Relations (PR)',
      'Security / Law Enforcement',
      'Telecom',
    ],
  },
];

export const ALL_DEPARTMENTS = DEPARTMENT_GROUPS.flatMap(g => g.options);
